-- ============================================================================
-- V1__init_billing_log.sql
-- M1 Week 3: 创建 billing_log 表
--
-- 设计要点(对应当前会话的 schema 讨论):
--   - 价格快照(input_unit_price / output_unit_price):每行落库不可变,
--     LLM 提供商未来调价不会污染历史账单
--   - 冗余列(total_tokens / total_cost / latency_ms):写入时一次算好,
--     避免月度聚合查询时反复重算
--   - request_id UNIQUE:计费幂等性基石,重试导致同请求被记账两次会直接抛异常
--   - user_id / session_id 现在留 NULL,M11 接 SSO 后启用,先建好列免得后期 ALTER
-- ============================================================================

CREATE TABLE billing_log (
                             id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             request_id          VARCHAR(36)     NOT NULL UNIQUE,
                             session_id          VARCHAR(64),
                             user_id             VARCHAR(64),

                             provider            VARCHAR(32)     NOT NULL,
                             model_name          VARCHAR(64)     NOT NULL,

                             input_tokens        INT             NOT NULL,
                             output_tokens       INT             NOT NULL,
                             total_tokens        INT             NOT NULL,

                             input_unit_price    DECIMAL(20, 10) NOT NULL,
                             output_unit_price   DECIMAL(20, 10) NOT NULL,
                             total_cost          DECIMAL(20, 6)  NOT NULL,
                             currency            VARCHAR(8)      NOT NULL DEFAULT 'CNY',

                             started_at          TIMESTAMP       NOT NULL,
                             completed_at        TIMESTAMP       NOT NULL,
                             latency_ms          INT             NOT NULL,

                             status              VARCHAR(16)     NOT NULL,
                             error_message       TEXT,

                             created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_billing_session ON billing_log(session_id, created_at);
CREATE INDEX idx_billing_model   ON billing_log(provider, model_name, created_at);