-- ============================================================================
-- V2__init_conversation_message.sql
-- M1 Week 3 Day 5: 创建 conversation_message 表(ChatMemoryStore 持久化层)
--
-- 设计要点(对应 ADR-007):
--   - 平字段 + 非平 JSON 混合存储:role/text/created_at 等"平"字段拆开存
--     (SQL 查询友好),ai_message_payload_json 保留 LangChain4j 自带
--     ChatMessageSerializer 生成的 AiMessage 整体 JSON(让框架兜底
--     text/thinking/toolExecutionRequests/attributes 等字段集随 1.x 版本演进,
--     Day 5 写的代码无需关心未来 LangChain4j 新增字段)
--   - text 列对 AI role 是冗余存储(payload_json 里也有),但保留是为了
--     SQL 查询/全文检索友好,这是结构化拆字段的初衷
--   - (conversation_id, message_index) UNIQUE:Day 5 走 delete-then-insert 时
--     不直接发挥作用,但保留未来切换到 upsert by index 策略的可能性,演进时不用改表
--   - tool_call_id / tool_name 仅 TOOL_EXECUTION_RESULT role 填:4 种 role
--     共用一张表的简洁性胜过拆 sub-table 的洁癖(ADR-007 已知代价 #4)
--   - conversation_id 即 LangChain4j memoryId,业务层称 conversationId
--     (CONTEXT.md v0.1.1 已定义)
--   - role VARCHAR(32):当前最长 TOOL_EXECUTION_RESULT 21 字符,留余量给未来
--     LangChain4j 新增消息类型(详见 MessageRole.java)
-- ============================================================================

CREATE TABLE conversation_message (
                                      id                              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      conversation_id                 VARCHAR(64)     NOT NULL,
                                      message_index                   INT             NOT NULL,

                                      role                            VARCHAR(32)     NOT NULL,
                                      text                            TEXT,

                                      ai_message_payload_json         TEXT,
                                      tool_call_id                    VARCHAR(64),
                                      tool_name                       VARCHAR(128),

                                      created_at                      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                      CONSTRAINT uk_conv_msg_idx UNIQUE (conversation_id, message_index)
);

CREATE INDEX idx_conv_msg_conv_id ON conversation_message(conversation_id);
